CREATE DATABASE IF NOT EXISTS crypfolio;

USE crypfolio;

CREATE TABLE `info_moneda` (
  `id` varchar(50) NOT NULL,
  `symbol` varchar(50) DEFAULT NULL,
  `moneda` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `info_moneda` (`id`, `symbol`, `moneda`) VALUES
('0x', 'zrx', '0x'),
('1inch', '1inch', '1inch'),
('3x-long-ethereum-token', 'ethbull', '3X Long Ethereum Token'),
('aave', 'aave', 'Aave'),
('aavegotchi', 'ghst', 'Aavegotchi'),
('adax', 'adax', 'ADAX'),
('adex', 'adx', 'AdEx'),
('aelf', 'elf', 'aelf'),
('aion', 'aion', 'Aion'),
('akash-network', 'akt', 'Akash Network'),
('akropolis', 'akro', 'Akropolis'),
('alchemix', 'alcx', 'Alchemix'),
('alchemix-usd', 'alusd', 'Alchemix USD'),
('alchemy-pay', 'ach', 'Alchemy Pay'),
('algorand', 'algo', 'Algorand'),
('alien-worlds', 'tlm', 'Alien Worlds'),
('allianceblock', 'albt', 'AllianceBlock'),
('alpaca-finance', 'alpaca', 'Alpaca Finance'),
('alpha-finance', 'alpha', 'Alpha Finance'),
('amp-token', 'amp', 'Amp'),
('ampleforth', 'ampl', 'Ampleforth'),
('ampleforth-governance-token', 'forth', 'Ampleforth Governance Token'),
('anchor-protocol', 'anc', 'Anchor Protocol'),
('ankr', 'ankr', 'Ankr'),
('ankreth', 'aeth', 'ankrETH'),
('apeswap-finance', 'banana', 'ApeSwap Finance'),
('api3', 'api3', 'API3'),
('aragon', 'ant', 'Aragon'),
('ardor', 'ardr', 'Ardor'),
('ark', 'ark', 'Ark'),
('arpa-chain', 'arpa', 'ARPA Chain'),
('artery', 'artr', 'Artery'),
('arweave', 'ar', 'Arweave'),
('asd', 'asd', 'AscendEx Token'),
('auction', 'auction', 'Bounce'),
('audius', 'audio', 'Audius'),
('augur', 'rep', 'Augur'),
('automata', 'ata', 'Automata'),
('avalanche-2', 'AVAX', 'Avalanche'),
('axie-infinity', 'axs', 'Axie Infinity'),
('badger-dao', 'badger', 'Badger DAO'),
('bakerytoken', 'bake', 'BakerySwap'),
('balancer', 'bal', 'Balancer'),
('bancor', 'bnt', 'Bancor Network Token'),
('band-protocol', 'band', 'Band Protocol'),
('barnbridge', 'bond', 'BarnBridge'),
('basic-attention-token', 'bat', 'Basic Attention Token'),
('beam', 'beam', 'BEAM'),
('beefy-finance', 'bifi', 'Beefy.Finance'),
('beldex', 'bdx', 'Beldex'),
('bella-protocol', 'bel', 'Bella Protocol'),
('benqi', 'qi', 'BENQI'),
('bepro-network', 'bepro', 'BEPRO Network'),
('bifrost', 'bfc', 'Bifrost'),
('binance-usd', 'busd', 'Binance USD'),
('binancecoin', 'bnb', 'Binance Coin'),
('bitclout', 'clout', 'BitClout'),
('bitcoin', 'btc', 'Bitcoin'),
('bitcoin-cash', 'bch', 'Bitcoin Cash'),
('bitcoin-cash-abc-2', 'bcha', 'Bitcoin Cash ABC'),
('bitcoin-cash-sv', 'bsv', 'Bitcoin SV'),
('bitcoin-diamond', 'bcd', 'Bitcoin Diamond'),
('bitcoin-gold', 'btg', 'Bitcoin Gold'),
('bitshares', 'bts', 'BitShares'),
('bittorrent-2', 'btt', 'BitTorrent'),
('blockstack', 'stx', 'Stacks'),
('bluzelle', 'blz', 'Bluzelle'),
('bonfida', 'fida', 'Bonfida'),
('boringdao-btc', 'obtc', 'BoringDAO BTC'),
('boson-protocol', 'boson', 'Boson Protocol'),
('btc-standard-hashrate-token', 'btcst', 'BTC Standard Hashrate Token'),
('btse-token', 'btse', 'BTSE Token'),
('bytecoin', 'bcn', 'Bytecoin'),
('bytom', 'btm', 'Bytom'),
('bzx-protocol', 'bzrx', 'bZx Protocol'),
('cardano', 'ada', 'Cardano'),
('cardstarter', 'cards', 'Cardstarter'),
('carry', 'cre', 'Carry'),
('cartesi', 'ctsi', 'Cartesi'),
('casper-network', 'cspr', 'Casper Network'),
('cdai', 'cdai', 'cDAI'),
('celer-network', 'celr', 'Celer Network'),
('celo', 'celo', 'Celo'),
('celsius-degree-token', 'cel', 'Celsius Network'),
('certik', 'ctk', 'CertiK'),
('chain-games', 'chain', 'Chain Games'),
('chainlink', 'link', 'Chainlink'),
('chia', 'xch', 'Chia'),
('chiliz', 'chz', 'Chiliz'),
('chromaway', 'chr', 'Chromia'),
('civic', 'cvc', 'Civic'),
('clover-finance', 'clv', 'Clover Finance'),
('cobak-token', 'cbk', 'Cobak Token'),
('coin98', 'c98', 'Coin98'),
('coinmetro', 'xcm', 'CoinMetro'),
('compound-0x', 'czrx', 'c0x'),
('compound-basic-attention-token', 'cbat', 'cBAT'),
('compound-ether', 'ceth', 'cETH'),
('compound-governance-token', 'comp', 'Compound'),
('compound-uniswap', 'cuni', 'cUNI'),
('compound-usd-coin', 'cusdc', 'cUSDC'),
('compound-usdt', 'cusdt', 'cUSDT'),
('concierge-io', 'ava', 'Travala.com'),
('conflux-token', 'cfx', 'Conflux'),
('constellation-labs', 'dag', 'Constellation'),
('contentos', 'cos', 'Contentos'),
('convex-crv', 'cvxcrv', 'Convex CRV'),
('convex-finance', 'cvx', 'Convex Finance'),
('cope', 'cope', 'Cope'),
('cosmos', 'atom', 'Cosmos'),
('coti', 'coti', 'COTI'),
('covalent', 'cqt', 'Covalent'),
('cream-2', 'cream', 'Cream'),
('cream-eth2', 'creth2', 'Cream ETH 2'),
('crust-network', 'cru', 'Crust Network'),
('crypto-com-chain', 'cro', 'Crypto.com Coin'),
('crypto20', 'c20', 'CRYPTO20'),
('curve-dao-token', 'crv', 'Curve DAO Token'),
('cvault-finance', 'core', 'cVault.finance'),
('dai', 'dai', 'Dai'),
('dao-maker', 'dao', 'DAO Maker'),
('dash', 'dash', 'Dash'),
('dawn-protocol', 'dawn', 'Dawn Protocol'),
('decentral-games', 'dg', 'Decentral Games'),
('decentraland', 'mana', 'Decentraland'),
('decred', 'dcr', 'Decred'),
('defipulse-index', 'dpi', 'DeFiPulse Index'),
('dent', 'dent', 'Dent'),
('derivadao', 'ddx', 'DerivaDAO'),
('dero', 'dero', 'Dero'),
('dextools', 'dext', 'DexTools'),
('dia-data', 'DIA', 'DIA'),
('digibyte', 'dgb', 'DigiByte'),
('digitalbits', 'xdb', 'DigitalBits'),
('district0x', 'dnt', 'district0x'),
('divi', 'divi', 'Divi'),
('dock', 'dock', 'Dock'),
('dodo', 'dodo', 'DODO'),
('dogecoin', 'doge', 'Dogecoin'),
('dvision-network', 'dvi', 'Dvision Network'),
('e-radix', 'exrd', 'e-Radix'),
('ecomi', 'omi', 'ECOMI'),
('eden', 'eden', 'EDEN'),
('elastos', 'ela', 'Elastos'),
('electroneum', 'etn', 'Electroneum'),
('ellipsis', 'eps', 'Ellipsis'),
('elrond-erd-2', 'egld', 'Elrond'),
('energi', 'nrg', 'Energi'),
('energy-web-token', 'ewt', 'Energy Web Token'),
('enjincoin', 'enj', 'Enjin Coin'),
('eos', 'eos', 'EOS'),
('ergo', 'erg', 'Ergo'),
('escoin-token', 'elg', 'Escoin Token'),
('eth-2x-flexible-leverage-index', 'ETH2x-FLI', 'ETH 2x Flexible Leverage Index'),
('ethereum', 'eth', 'Ethereum'),
('ethereum-classic', 'etc', 'Ethereum Classic'),
('ethernity-chain', 'ern', 'Ethernity Chain'),
('ethlend', 'lend', 'Aave [OLD]'),
('everipedia', 'iq', 'Everipedia'),
('evolution-finance', 'evn', 'Evolution Finance'),
('exeedme', 'xed', 'Exeedme'),
('fantom', 'ftm', 'Fantom'),
('feg-token', 'feg', 'FEG Token'),
('fei-protocol', 'fei', 'Fei Protocol'),
('fetch-ai', 'fet', 'Fetch.ai'),
('filecoin', 'fil', 'Filecoin'),
('fio-protocol', 'fio', 'FIO Protocol'),
('flex-coin', 'flex', 'FLEX Coin'),
('flow', 'flow', 'Flow'),
('frax', 'frax', 'Frax'),
('frax-share', 'fxs', 'Frax Share'),
('friends-with-benefits-pro', 'fwb', 'Friends With Benefits Pro'),
('ftx-token', 'ftt', 'FTX Token'),
('funfair', 'fun', 'FUNToken'),
('futureswap', 'fst', 'Futureswap'),
('fx-coin', 'fx', 'Function X'),
('gala', 'gala', 'Gala'),
('gas', 'gas', 'Gas'),
('gatechain-token', 'gt', 'GateToken'),
('gemini-dollar', 'gusd', 'Gemini Dollar'),
('gerowallet', 'gero', 'GeroWallet'),
('gitcoin', 'gtc', 'Gitcoin'),
('gnosis', 'gno', 'Gnosis'),
('gny', 'gny', 'GNY'),
('golem', 'glm', 'Golem'),
('governance-zil', 'gzil', 'governance ZIL'),
('groestlcoin', 'grs', 'Groestlcoin'),
('handshake', 'hns', 'Handshake'),
('hard-protocol', 'HARD', 'HARD Protocol'),
('harmony', 'one', 'Harmony'),
('harvest-finance', 'farm', 'Harvest Finance'),
('hathor', 'htr', 'Hathor'),
('haven', 'xhv', 'Haven'),
('havven', 'snx', 'Synthetix Network Token'),
('hbtc-token', 'hbc', 'HBTC Captain Token'),
('hedera-hashgraph', 'hbar', 'Hedera Hashgraph'),
('hegic', 'hegic', 'Hegic'),
('helium', 'hnt', 'Helium'),
('hi-dollar', 'hi', 'hi Dollar'),
('hive', 'hive', 'Hive'),
('hoge-finance', 'hoge', 'Hoge Finance'),
('holotoken', 'hot', 'Holo'),
('huobi-btc', 'hbtc', 'Huobi BTC'),
('huobi-token', 'ht', 'Huobi Token'),
('husd', 'husd', 'HUSD'),
('hxro', 'hxro', 'Hxro'),
('hydra', 'hydra', 'Hydra'),
('icon', 'icx', 'ICON'),
('iexec-rlc', 'rlc', 'iExec RLC'),
('illuvium', 'ilv', 'Illuvium'),
('index-cooperative', 'index', 'Index Cooperative'),
('injective-protocol', 'inj', 'Injective Protocol'),
('instadapp', 'inst', 'Instadapp'),
('insure', 'sure', 'inSure DeFi'),
('internet-computer', 'icp', 'Internet Computer'),
('iostoken', 'iost', 'IOST'),
('iota', 'miota', 'IOTA'),
('iotex', 'iotx', 'IoTeX'),
('iris-network', 'iris', 'IRISnet'),
('joe', 'joe', 'JOE'),
('just', 'jst', 'JUST'),
('kadena', 'kda', 'Kadena'),
('kardiachain', 'kai', 'KardiaChain'),
('kava', 'kava', 'Kava.io'),
('keep-network', 'keep', 'Keep Network'),
('kin', 'kin', 'Kin'),
('kirobo', 'kiro', 'Kirobo'),
('klay-token', 'klay', 'Klaytn'),
('kleros', 'pnk', 'Kleros'),
('klever', 'klv', 'Klever'),
('komodo', 'kmd', 'Komodo'),
('kucoin-shares', 'kcs', 'KuCoin Token'),
('kusama', 'ksm', 'Kusama'),
('kyber-network', 'kncl', 'Kyber Network Crystal Legacy'),
('kyber-network-crystal', 'knc', 'Kyber Network Crystal'),
('lattice-token', 'ltx', 'Lattice Token'),
('ledgis', 'led', 'Ledgis'),
('legolas-exchange', 'lgo', 'LGO Token'),
('leo-token', 'leo', 'LEO Token'),
('lgcy-network', 'lgcy', 'LGCY Network'),
('lido-dao', 'ldo', 'Lido DAO'),
('linear', 'lina', 'Linear'),
('link', 'ln', 'LINK'),
('liquity-usd', 'lusd', 'Liquity USD'),
('lisk', 'lsk', 'Lisk'),
('litecoin', 'ltc', 'Litecoin'),
('litentry', 'lit', 'Litentry'),
('livepeer', 'lpt', 'Livepeer'),
('lockchain', 'loc', 'LockTrip'),
('loom-network', 'loomold', 'Loom Network (OLD)'),
('loopring', 'lrc', 'Loopring'),
('lto-network', 'lto', 'LTO Network'),
('lukso-token', 'lyxe', 'LUKSO Token'),
('maidsafecoin', 'maid', 'MaidSafeCoin'),
('mainframe', 'mft', 'Hifi Finance'),
('maker', 'mkr', 'Maker'),
('manchester-city-fan-token', 'city', 'Manchester City Fan Token'),
('mango-markets', 'mngo', 'Mango Markets'),
('mantra-dao', 'om', 'MANTRA DAO'),
('maps', 'maps', 'MAPS'),
('marketpeak', 'peak', 'PEAKDEFI'),
('marlin', 'pond', 'Marlin'),
('mask-network', 'mask', 'Mask Network'),
('mass', 'mass', 'MASS'),
('math', 'math', 'MATH'),
('matic-network', 'matic', 'Polygon'),
('mcdex', 'mcb', 'MCDEX'),
('mdex', 'mdx', 'Mdex'),
('medibloc', 'med', 'Medibloc'),
('melon', 'mln', 'Enzyme'),
('metadium', 'meta', 'Metadium'),
('metahero', 'hero', 'Metahero'),
('metal', 'mtl', 'Metal'),
('mina-protocol', 'mina', 'Mina Protocol'),
('mirror-protocol', 'mir', 'Mirror Protocol'),
('mobox', 'mbox', 'Mobox'),
('monacoin', 'mona', 'MonaCoin'),
('monero', 'xmr', 'Monero'),
('mx-token', 'mx', 'MX Token'),
('mxc', 'mxc', 'MXC'),
('my-neighbor-alice', 'alice', 'My Neighbor Alice'),
('nano', 'nano', 'Nano'),
('naos-finance', 'naos', 'NAOS Finance'),
('near', 'near', 'Near'),
('nem', 'xem', 'NEM'),
('neo', 'neo', 'NEO'),
('nerve-finance', 'nrv', 'Nerve Finance'),
('nervos-network', 'ckb', 'Nervos Network'),
('neutrino', 'usdn', 'Neutrino USD'),
('newscrypto-coin', 'nwc', 'Newscrypto Coin'),
('nexo', 'nexo', 'NEXO'),
('nftx', 'nftx', 'NFTX'),
('nkn', 'nkn', 'NKN'),
('noia-network', 'noia', 'Syntropy'),
('nominex', 'nmx', 'Nominex'),
('nucypher', 'nu', 'NuCypher'),
('numeraire', 'nmr', 'Numeraire'),
('nusd', 'susd', 'sUSD'),
('nxm', 'nxm', 'Nexus Mutual'),
('o3-swap', 'o3', 'O3 Swap'),
('oasis-network', 'rose', 'Oasis Network'),
('occamfi', 'occ', 'OccamFi'),
('ocean-protocol', 'ocean', 'Ocean Protocol'),
('okb', 'okb', 'OKB'),
('olympus', 'ohm', 'Olympus'),
('omisego', 'omg', 'OMG Network'),
('ontology', 'ont', 'Ontology'),
('orbs', 'orbs', 'Orbs'),
('orchid-protocol', 'oxt', 'Orchid Protocol'),
('origin-protocol', 'ogn', 'Origin Protocol'),
('origintrail', 'trac', 'OriginTrail'),
('orion-protocol', 'orn', 'Orion Protocol'),
('osmosis', 'osmo', 'Osmosis'),
('oxygen', 'oxy', 'Oxygen'),
('paccoin', 'pac', 'PAC Protocol'),
('paid-network', 'paid', 'PAID Network'),
('pancakeswap-token', 'cake', 'PancakeSwap'),
('pangolin', 'png', 'Pangolin'),
('paris-saint-germain-fan-token', 'psg', 'Paris Saint-Germain Fan Token'),
('parsiq', 'prq', 'PARSIQ'),
('pax-gold', 'paxg', 'PAX Gold'),
('paxos-standard', 'usdp', 'Pax Dollar'),
('perpetual-protocol', 'perp', 'Perpetual Protocol'),
('persistence', 'xprt', 'Persistence'),
('pha', 'pha', 'Phala Network'),
('pirate-chain', 'arrr', 'Pirate Chain'),
('plant-vs-undead-token', 'pvu', 'Plant vs Undead Token'),
('playdapp', 'pla', 'PlayDapp'),
('plex', 'plex', 'PLEX'),
('polkadot', 'dot', 'Polkadot'),
('polkastarter', 'pols', 'Polkastarter'),
('polymath', 'poly', 'Polymath'),
('populous', 'ppt', 'Populous'),
('power-ledger', 'powr', 'Power Ledger'),
('privateum', 'pvm', 'Privateum'),
('prometeus', 'prom', 'Prometeus'),
('ptokens-btc', 'pbtc', 'pTokens BTC'),
('pundi-x', 'npxs', 'Pundi X [OLD]'),
('pundi-x-2', 'pundix', 'Pundi X'),
('pylon-protocol', 'mine', 'Pylon Protocol'),
('qtum', 'qtum', 'Qtum'),
('quant-network', 'qnt', 'Quant'),
('quark-chain', 'qkc', 'QuarkChain'),
('quick', 'quick', 'Quickswap'),
('radicle', 'rad', 'Radicle'),
('rally-2', 'rly', 'Rally'),
('ramp', 'ramp', 'RAMP'),
('rari-governance-token', 'rgt', 'Rari Governance Token'),
('rarible', 'rari', 'Rarible'),
('ravencoin', 'rvn', 'Ravencoin'),
('raydium', 'ray', 'Raydium'),
('reddcoin', 'rdd', 'Reddcoin'),
('redfox-labs-2', 'rfox', 'RedFOX Labs'),
('reef-finance', 'reef', 'Reef Finance'),
('refereum', 'rfr', 'Refereum'),
('renbtc', 'renbtc', 'renBTC'),
('render-token', 'rndr', 'Render Token'),
('republic-protocol', 'ren', 'REN'),
('request-network', 'req', 'Request'),
('reserve-rights-token', 'rsr', 'Reserve Rights Token'),
('rif-token', 'rif', 'RSK Infrastructure Framework'),
('ripple', 'xrp', 'XRP'),
('rocket-pool', 'rpl', 'Rocket Pool'),
('rook', 'rook', 'KeeperDAO'),
('safemoon', 'safemoon', 'SafeMoon'),
('safepal', 'sfp', 'SafePal'),
('saffron-finance', 'sfi', 'saffron.finance'),
('sapphire', 'sapp', 'Sapphire'),
('sbtc', 'sbtc', 'sBTC'),
('secret', 'scrt', 'Secret'),
('sentinel', 'dvpn', 'Sentinel'),
('sentinel-protocol', 'upp', 'Sentinel Protocol'),
('serum', 'srm', 'Serum'),
('seth', 'seth', 'sETH'),
('seth2', 'seth2', 'sETH2'),
('seur', 'seur', 'sEUR'),
('sharering', 'shr', 'ShareToken'),
('shiba-inu', 'shib', 'Shiba Inu'),
('shopping-io', 'spi', 'Shopping.io'),
('siacoin', 'sc', 'Siacoin'),
('singularitynet', 'agix', 'SingularityNET'),
('skale', 'skl', 'SKALE'),
('slink', 'slink', 'sLINK'),
('smooth-love-potion', 'slp', 'Smooth Love Potion'),
('solana', 'sol', 'Solana'),
('sonm', 'snm', 'SONM'),
('sora', 'xor', 'Sora'),
('sora-validator-token', 'val', 'Sora Validator Token'),
('stablexswap', 'stax', 'StableXSwap'),
('stafi', 'fis', 'Stafi'),
('staked-ether', 'steth', 'Lido Staked Ether'),
('stakehound-staked-ether', 'steth', 'StakeHound Staked Ether'),
('starlink', 'starl', 'StarLink'),
('stasis-eurs', 'eurs', 'STASIS EURO'),
('status', 'SNT', 'Status'),
('steem', 'steem', 'Steem'),
('steem-dollars', 'sbd', 'Steem Dollars'),
('stellar', 'xlm', 'Stellar'),
('storj', 'storj', 'Storj'),
('storm', 'stmx', 'StormX'),
('stp-network', 'stpt', 'STP Network'),
('stratis', 'strax', 'Stratis'),
('streamr-xdata', 'xdata', 'Streamr XDATA'),
('strong', 'strong', 'Strong'),
('suku', 'SUKU', 'SUKU'),
('sun-token', 'sun', 'Sun Token'),
('superfarm', 'super', 'SuperFarm'),
('superrare', 'rare', 'SuperRare'),
('sushi', 'sushi', 'Sushi'),
('swipe', 'sxp', 'Swipe'),
('swissborg', 'chsb', 'SwissBorg'),
('syscoin', 'sys', 'Syscoin'),
('telcoin', 'tel', 'Telcoin'),
('tellor', 'trb', 'Tellor'),
('telos', 'tlos', 'Telos'),
('tenset', '10set', 'Tenset'),
('terra-luna', 'luna', 'Terra'),
('terra-virtua-kolect', 'tvk', 'Terra Virtua Kolect'),
('terrausd', 'ust', 'TerraUSD'),
('tether', 'usdt', 'Tether'),
('tether-gold', 'xaut', 'Tether Gold'),
('tezos', 'xtz', 'Tezos'),
('the-graph', 'grt', 'The Graph'),
('the-sandbox', 'sand', 'The Sandbox'),
('the-truth', 'ufo', 'The Truth'),
('theta-fuel', 'tfuel', 'Theta Fuel'),
('theta-token', 'theta', 'Theta Network'),
('thorchain', 'rune', 'THORChain'),
('thorchain-erc20', 'rune', 'THORChain (ERC20)'),
('thorstarter', 'xrune', 'Thorstarter'),
('thunder-token', 'tt', 'ThunderCore'),
('titanswap', 'titan', 'TitanSwap'),
('tokamak-network', 'ton', 'Tokamak Network'),
('tokemak', 'toke', 'Tokemak'),
('token-pocket', 'tpt', 'Token Pocket'),
('tokenlon', 'lon', 'Tokenlon'),
('tokocrypto', 'tko', 'Tokocrypto'),
('tomochain', 'tomo', 'TomoChain'),
('ton-crystal', 'ton', 'TON Crystal'),
('tornado-cash', 'torn', 'Tornado Cash'),
('tribe-2', 'tribe', 'Tribe'),
('tron', 'trx', 'TRON'),
('true-usd', 'tusd', 'TrueUSD'),
('truefi', 'tru', 'TrueFi'),
('trust-wallet-token', 'twt', 'Trust Wallet Token'),
('trustswap', 'swap', 'Trustswap'),
('ultra', 'uos', 'Ultra'),
('uma', 'uma', 'UMA'),
('unfederalreserve', 'ersdl', 'unFederalReserve'),
('unibright', 'ubt', 'Unibright'),
('uniswap', 'uni', 'Uniswap'),
('unit-protocol', 'col', 'Unit Protocol'),
('universe-xyz', 'xyz', 'Universe.XYZ'),
('unizen', 'zcx', 'Unizen'),
('uquid-coin', 'uqc', 'Uquid Coin'),
('usd-coin', 'usdc', 'USD Coin'),
('usdp', 'usdp', 'USDP Stablecoin'),
('usdx', 'usdx', 'USDX'),
('utrust', 'utk', 'UTRUST'),
('vai', 'vai', 'Vai'),
('vechain', 'vet', 'VeChain'),
('vectorspace', 'vxv', 'Vectorspace AI'),
('velas', 'vlx', 'Velas'),
('venus', 'xvs', 'Venus'),
('verasity', 'vra', 'Verasity'),
('verge', 'xvg', 'Verge'),
('verus-coin', 'vrsc', 'Verus Coin'),
('vethor-token', 'vtho', 'VeThor Token'),
('videocoin', 'vid', 'VideoCoin'),
('vite', 'vite', 'Vite'),
('vulcan-forged', 'pyr', 'Vulcan Forged'),
('wanchain', 'wan', 'Wanchain'),
('waves', 'waves', 'Waves'),
('waves-ducks', 'egg', 'Waves Ducks'),
('wax', 'waxp', 'WAX'),
('wazirx', 'wrx', 'WazirX'),
('whale', 'whale', 'WHALE'),
('wilder-world', 'wild', 'Wilder World'),
('wink', 'win', 'WINkLink'),
('woo-network', 'woo', 'WOO Network'),
('woonkly-power', 'woop', 'Woonkly Power'),
('wozx', 'wozx', 'Efforce'),
('wpp-token', 'wpp', 'WPP Token'),
('wrapped-bitcoin', 'wbtc', 'Wrapped Bitcoin'),
('wrapped-centrifuge', 'wcfg', 'Wrapped Centrifuge'),
('wrapped-nxm', 'wnxm', 'Wrapped NXM'),
('xdce-crowd-sale', 'xdc', 'XDC Network'),
('xsushi', 'xsushi', 'xSUSHI'),
('xyo-network', 'xyo', 'XYO Network'),
('yearn-finance', 'yfi', 'yearn.finance'),
('yfii-finance', 'yfii', 'DFI.money'),
('yield-guild-games', 'ygg', 'Yield Guild Games'),
('zcash', 'zec', 'Zcash'),
('zcoin', 'firo', 'Firo'),
('zencash', 'zen', 'Horizen'),
('zenon', 'znn', 'Zenon'),
('zero-collateral-dai', 'zai', 'Zero Collateral Dai'),
('zilliqa', 'zil', 'Zilliqa'),
('zipmex-token', 'zmt', 'Zipmex Token'),
('zkswap', 'zks', 'ZKSwap');


CREATE TABLE `moneda_portfolio` (
  `id` int(11) NOT NULL,
  `cantidad` float NOT NULL,
  `coste_medio` float NOT NULL,
  `moneda` varchar(255) NOT NULL,
  `symbol` varchar(255) NOT NULL,
  `usuario_nombre_usuario` int(11) NOT NULL,
  `id_moneda` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;


CREATE TABLE `rol` (
  `id` int(11) NOT NULL,
  `rol_nombre` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

INSERT INTO `rol` (`id`, `rol_nombre`) VALUES
(1, 'ROLE_ADMIN'),
(2, 'ROLE_USER');


CREATE TABLE `usuario` (
  `id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `nombre_usuario` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;


CREATE TABLE `usuario_rol` (
  `usuario_id` int(11) NOT NULL,
  `rol_id` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;



ALTER TABLE `info_moneda`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `moneda_portfolio`
  ADD PRIMARY KEY (`id`),
  ADD KEY `FK3444fmxtvi53ageesy59nhr0h` (`usuario_nombre_usuario`);


ALTER TABLE `rol`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `usuario`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UK_puhr3k3l7bj71hb7hk7ktpxn0` (`nombre_usuario`) USING HASH;


ALTER TABLE `usuario_rol`
  ADD PRIMARY KEY (`usuario_id`,`rol_id`),
  ADD KEY `FK610kvhkwcqk2pxeewur4l7bd1` (`rol_id`);


ALTER TABLE `moneda_portfolio`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `rol`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `usuario`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
